# Generated by Django 3.2.4 on 2021-06-17 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=25)),
                ('contrasenia', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('numero_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Doble', 'Doble')], max_length=25)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignada', 'Asignada'), ('En Mantención', 'En Mantención')], max_length=25)),
                ('tipo_cama', models.CharField(choices=[('Individual', 'Individual'), ('Queen', 'Queen'), ('King', 'King')], max_length=25)),
                ('accesorios', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('familia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_elaboracion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimineto', models.DateField(default=django.utils.timezone.now)),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro_proveedor',
            fields=[
                ('id_rubro', models.BigAutoField(primary_key=True, serialize=False)),
                ('rubro', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut_usuarios', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=2)),
                ('nombre_usuario', models.CharField(max_length=80)),
                ('perfil', models.CharField(choices=[('cambiar', 'cambiar'), ('agregar', 'agregar')], max_length=25)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('inicio_actividades', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True, verbose_name='Eres un usuario activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('id_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.rubro_proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_pedido',
            fields=[
                ('numero_orden_p', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rut_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.proveedor')),
            ],
        ),
    ]
