# Generated by Django 3.2.4 on 2021-06-26 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actual', models.DateField(default=django.utils.timezone.now)),
                ('total_cantidad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='neto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.IntegerField(),
        ),
    ]
