# Generated by Django 3.2.4 on 2021-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombres', models.CharField(max_length=25)),
                ('a_paterno', models.CharField(max_length=25)),
                ('a_materno', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=25)),
                ('contrasenia', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
