# Generated by Django 3.1.2 on 2021-07-15 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('rut_huesped', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField(default=datetime.date.today)),
                ('fecha_hasta', models.DateField(default=datetime.date.today)),
                ('vigente', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Individual Premium', 'Individual Premium'), ('Doble', 'Doble'), ('Loft', 'Loft')], max_length=25),
        ),
        migrations.CreateModel(
            name='ReservaHuesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.habitacion')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reserva')),
                ('rut_huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.huesped')),
            ],
        ),
    ]
