# Generated by Django 3.0.8 on 2021-06-24 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('codigo_plato', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo_comida', models.CharField(max_length=25)),
                ('dia', models.DateField(default=django.utils.timezone.now)),
                ('precio', models.IntegerField()),
                ('codigo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Servicio')),
            ],
        ),
    ]
