# Generated by Django 3.2.4 on 2021-06-18 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210617_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenesdecompra',
            fields=[
                ('numero_orden_c', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(default=django.utils.timezone.now)),
                ('total_dias', models.IntegerField()),
                ('total_huespedes', models.IntegerField()),
            ],
        ),
    ]
