# Generated by Django 3.2.4 on 2021-06-26 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210626_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_elaboracion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
