# Generated by Django 3.2.4 on 2021-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210626_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='total_cantidad',
            field=models.CharField(max_length=100),
        ),
    ]
